### ISSUE TITLE
Test Lua script example

### ISSUE THREAD

**Issue by GrimmAndreas** [inmation/inmation-api-docs#1]
Hello Bjorn,
we would like test your Lua script example withe the Swagger.
The call with out parameters is ok ("Hello unknown"). But what is the syntax of the parameters for an other answer.
Andreas

**Comment by Longmountain** [comment]
Your Swagger 'execfunction' POST call could have a body which looks like:

```json
{
  "data": {
    "lib": "mylibrary",
    "func": "say_hello",
    "farg": {
        "name": "people"
    }
  }
}
```

**Comment by GrimmAndreas** [comment]
Thanks alot, for your prompt answer. This combination I don't have tested.
